server:
  port: PORT

db:
  host: RDS_HOSTNAME
  port: RDS_PORT
  database: RDS_DB_NAME
  username: RDS_USERNAME
  password: RDS_PASSWORD
  synchronize: TYPEORM_SYNC

jwt:
  secret: JWT_SECRET # @TODO simple - is not good practise (!)
